### ISSUE TITLE
increase diversity 

### ISSUE THREAD

**Issue by ngam** [conda-incubator/governance#75]
https://github.com/conda-incubator/governance/blob/main/steering.csv

Any serious plans to add non-"he/him" to this list? If so, I am interested in checking them out.

Currently, 12/16 are "he/him", assuming the others are unknown/tbd.

**Comment by msarahan** [comment]
This is not by design. Conda-forge and the greater conda community have grown organically, and the list here represents people who have been active long enough to feel responsible/obligated to act for the community.

This is to say that you should not read the current state of pronouns as the way that any of us wants it to be. If you or anyone else would like to help us be a more diverse group, I hope you will consider joining us. The steering council here has a minimum size but not a maximum size. I'd be happy to help nominate you or anyone who has shown activity in the conda/conda-forge ecosystem and who has an interest in helping improve the ecosystem.
